### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by bemoregt** [carpedm20/BEGAN-pytorch#8]
Hi, @dribnet @carpedm20 @scott-vsi 

I met this error:

ctilab@ctilab:~/BEGAN-pytorch$ python main.py  --dataset=images --num_gpu=0
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import torch
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

What's wrong with me?

**Comment by bemoregt** [comment]
I solved it.

sudo pip install -U numpy

**Comment by Red-Eyed** [comment]
I solved it w/o sudo:
`pip install numpy --user`

**Comment by mohamed1408** [comment]
![images](https://user-images.githubusercontent.com/51641929/80116235-588cb000-85a3-11ea-897b-f4db1f7fb4d0.jpg)
